name: Deploy Profile Manager on Change

on:
  push:
    paths:
      - "profile_manager/**"

jobs:
  deploy-profile-manager:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build profile-manager
        run: |
          cd profile-manager
          npm install
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: profile-manager/build
